# Generated by Django 3.0.3 on 2020-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
